import type { EnemyStats, EnemyType } from '../types/entities';

export interface EnemyDefinition {
  type: EnemyType;
  name: string;
  color: number;
  size: number; // radius px
  baseStats: EnemyStats;
}

export const ENEMY_DEFINITIONS: Record<EnemyType, EnemyDefinition> = {
  walker: {
    type: 'walker',
    name: 'Walker',
    color: 0xff4444,
    size: 16,
    baseStats: {
      maxHp: 40,
      hp: 40,
      speed: 80,
      defense: 0,
      attackDamage: 10,
      attackSpeed: 1,
      attackRange: 24,
      xpReward: 10,
      scoreReward: 5,
      knockbackResistance: 0,
    },
  },
  runner: {
    type: 'runner',
    name: 'Runner',
    color: 0xff8844,
    size: 12,
    baseStats: {
      maxHp: 25,
      hp: 25,
      speed: 160,
      defense: 0,
      attackDamage: 15,
      attackSpeed: 1.5,
      attackRange: 20,
      xpReward: 15,
      scoreReward: 8,
      knockbackResistance: 0,
    },
  },
  tank: {
    type: 'tank',
    name: 'Tank',
    color: 0xaa2222,
    size: 24,
    baseStats: {
      maxHp: 200,
      hp: 200,
      speed: 55,
      defense: 15,
      attackDamage: 30,
      attackSpeed: 0.5,
      attackRange: 30,
      xpReward: 30,
      scoreReward: 20,
      knockbackResistance: 0.7,
    },
  },
  ranged: {
    type: 'ranged',
    name: 'Ranged',
    color: 0xff44aa,
    size: 14,
    baseStats: {
      maxHp: 30,
      hp: 30,
      speed: 70,
      defense: 0,
      attackDamage: 20,
      attackSpeed: 0.8,
      attackRange: 200,
      xpReward: 20,
      scoreReward: 12,
      knockbackResistance: 0,
    },
  },
  exploder: {
    type: 'exploder',
    name: 'Exploder',
    color: 0xffaa00,
    size: 18,
    baseStats: {
      maxHp: 35,
      hp: 35,
      speed: 110,
      defense: 0,
      attackDamage: 60,
      attackSpeed: 0,
      attackRange: 40,
      xpReward: 25,
      scoreReward: 15,
      knockbackResistance: 0,
    },
  },
  flyer: {
    type: 'flyer',
    name: 'Flyer',
    color: 0x88ccff,
    size: 12,
    baseStats: {
      maxHp: 20,
      hp: 20,
      speed: 130,
      defense: 0,
      attackDamage: 8,
      attackSpeed: 1.2,
      attackRange: 20,
      xpReward: 12,
      scoreReward: 8,
      knockbackResistance: 0,
    },
  },
  splitter: {
    type: 'splitter',
    name: 'Splitter',
    color: 0x44ff88,
    size: 20,
    baseStats: {
      maxHp: 80,
      hp: 80,
      speed: 75,
      defense: 5,
      attackDamage: 15,
      attackSpeed: 0.8,
      attackRange: 24,
      xpReward: 20,
      scoreReward: 15,
      knockbackResistance: 0.3,
    },
  },
  shielder: {
    type: 'shielder',
    name: 'Shielder',
    color: 0x4466ff,
    size: 18,
    baseStats: {
      maxHp: 120,
      hp: 120,
      speed: 65,
      defense: 20,
      attackDamage: 20,
      attackSpeed: 0.7,
      attackRange: 28,
      xpReward: 25,
      scoreReward: 18,
      knockbackResistance: 0.5,
    },
  },
  healer: {
    type: 'healer',
    name: 'Healer',
    color: 0x66ff66,
    size: 14,
    baseStats: {
      maxHp: 45,
      hp: 45,
      speed: 70,
      defense: 0,
      attackDamage: 5,
      attackSpeed: 0.5,
      attackRange: 20,
      xpReward: 30,
      scoreReward: 25,
      knockbackResistance: 0,
    },
  },
  boss_titan: {
    type: 'boss_titan',
    name: 'The Titan',
    color: 0x882222,
    size: 48,
    baseStats: {
      maxHp: 2000,
      hp: 2000,
      speed: 65,
      defense: 30,
      attackDamage: 80,
      attackSpeed: 0.4,
      attackRange: 60,
      xpReward: 500,
      scoreReward: 1000,
      knockbackResistance: 0.95,
    },
  },
  boss_hydra: {
    type: 'boss_hydra',
    name: 'The Hydra',
    color: 0x228844,
    size: 56,
    baseStats: {
      maxHp: 4000,
      hp: 4000,
      speed: 50,
      defense: 20,
      attackDamage: 60,
      attackSpeed: 0.5,
      attackRange: 200,
      xpReward: 1000,
      scoreReward: 2000,
      knockbackResistance: 0.98,
    },
  },
  boss_lich: {
    type: 'boss_lich',
    name: 'The Lich',
    color: 0x6622aa,
    size: 44,
    baseStats: {
      maxHp: 3500,
      hp: 3500,
      speed: 60,
      defense: 15,
      attackDamage: 50,
      attackSpeed: 0.6,
      attackRange: 250,
      xpReward: 1500,
      scoreReward: 3000,
      knockbackResistance: 0.95,
    },
  },
};
