import type { EnemyStats, EnemyType } from '../types/entities';

export interface EnemyDefinition {
  type: EnemyType;
  name: string;
  color: number;
  size: number; // radius px
  baseStats: EnemyStats;
}

export const ENEMY_DEFINITIONS = {
  walker: {
    type: 'walker',
    name: 'Walker',
    color: 0xff4444,
    size: 16,
    baseStats: {
      maxHp: 50,
      hp: 50,
      speed: 120,
      defense: 0,
      attackDamage: 11,
      attackSpeed: 1,
      attackRange: 24,
      xpReward: 10,
      scoreReward: 5,
      knockbackResistance: 0,
    },
  },
  runner: {
    type: 'runner',
    name: 'Runner',
    color: 0xff8844,
    size: 12,
    baseStats: {
      maxHp: 30,
      hp: 30,
      speed: 190,
      defense: 0,
      attackDamage: 17,
      attackSpeed: 1.5,
      attackRange: 20,
      xpReward: 15,
      scoreReward: 8,
      knockbackResistance: 0,
    },
  },
  tank: {
    type: 'tank',
    name: 'Tank',
    color: 0xaa2222,
    size: 24,
    baseStats: {
      maxHp: 240,
      hp: 240,
      speed: 75,
      defense: 18,
      attackDamage: 33,
      attackSpeed: 0.5,
      attackRange: 30,
      xpReward: 30,
      scoreReward: 20,
      knockbackResistance: 0.7,
    },
  },
  ranged: {
    type: 'ranged',
    name: 'Ranged',
    color: 0xff44aa,
    size: 14,
    baseStats: {
      maxHp: 36,
      hp: 36,
      speed: 70,
      defense: 0,
      attackDamage: 22,
      attackSpeed: 0.8,
      attackRange: 200,
      xpReward: 20,
      scoreReward: 12,
      knockbackResistance: 0,
    },
  },
  exploder: {
    type: 'exploder',
    name: 'Exploder',
    color: 0xffaa00,
    size: 18,
    baseStats: {
      maxHp: 42,
      hp: 42,
      speed: 110,
      defense: 0,
      attackDamage: 45,
      attackSpeed: 0,
      attackRange: 40,
      xpReward: 25,
      scoreReward: 15,
      knockbackResistance: 0,
    },
  },
  flyer: {
    type: 'flyer',
    name: 'Flyer',
    color: 0x88ccff,
    size: 12,
    baseStats: {
      maxHp: 25,
      hp: 25,
      speed: 130,
      defense: 0,
      attackDamage: 9,
      attackSpeed: 1.2,
      attackRange: 20,
      xpReward: 12,
      scoreReward: 8,
      knockbackResistance: 0,
    },
  },
  splitter: {
    type: 'splitter',
    name: 'Splitter',
    color: 0x44ff88,
    size: 20,
    baseStats: {
      maxHp: 95,
      hp: 95,
      speed: 75,
      defense: 5,
      attackDamage: 17,
      attackSpeed: 0.8,
      attackRange: 24,
      xpReward: 20,
      scoreReward: 15,
      knockbackResistance: 0.3,
    },
  },
  shielder: {
    type: 'shielder',
    name: 'Shielder',
    color: 0x4466ff,
    size: 18,
    baseStats: {
      maxHp: 145,
      hp: 145,
      speed: 65,
      defense: 22,
      attackDamage: 22,
      attackSpeed: 0.7,
      attackRange: 28,
      xpReward: 25,
      scoreReward: 18,
      knockbackResistance: 0.5,
    },
  },
  healer: {
    type: 'healer',
    name: 'Healer',
    color: 0x66ff66,
    size: 14,
    baseStats: {
      maxHp: 55,
      hp: 55,
      speed: 70,
      defense: 0,
      attackDamage: 6,
      attackSpeed: 0.5,
      attackRange: 20,
      xpReward: 30,
      scoreReward: 25,
      knockbackResistance: 0,
    },
  },
  boss_goblin_king: {
    type: 'boss_goblin_king',
    name: 'King Goblin',
    color: 0x44aa22,
    size: 40,
    baseStats: {
      maxHp: 1800,
      hp: 1800,
      speed: 85,
      defense: 20,
      attackDamage: 60,
      attackSpeed: 0.6,
      attackRange: 50,
      xpReward: 500,
      scoreReward: 1000,
      knockbackResistance: 0.85,
    },
  },
  boss_hydra: {
    type: 'boss_hydra',
    name: 'The Hydra',
    color: 0x228844,
    size: 56,
    baseStats: {
      maxHp: 4000,
      hp: 4000,
      speed: 50,
      defense: 20,
      attackDamage: 60,
      attackSpeed: 0.5,
      attackRange: 200,
      xpReward: 1000,
      scoreReward: 2000,
      knockbackResistance: 0.98,
    },
  },
  boss_lich: {
    type: 'boss_lich',
    name: 'The Lich',
    color: 0x6622aa,
    size: 44,
    baseStats: {
      maxHp: 3500,
      hp: 3500,
      speed: 60,
      defense: 15,
      attackDamage: 50,
      attackSpeed: 0.6,
      attackRange: 250,
      xpReward: 1500,
      scoreReward: 3000,
      knockbackResistance: 0.95,
    },
  },
} as const satisfies Record<EnemyType, EnemyDefinition>;
